# -*- coding: utf-8 -*-
"""Bank account system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Az9mXis6H3LmphkXKIiHvRGmG1p9t-E-
"""

class BankAccount:
    def __init__(self, account_number, customer_name, balance):
        self.account_number = account_number
        self.customer_name = customer_name
        self.balance = balance

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            print("Rs.", amount, "deposited successfully.")
        else:
            print("Invalid deposit amount.")

    def withdraw(self, amount):
        if amount > 0 and amount <= self.balance:
            self.balance -= amount
            print("Rs.", amount, "withdrawn successfully.")
        else:
            print("Insufficient balance or invalid amount.")

    def check_balance(self):
        print("Current Balance: Rs.", self.balance)

    def calculate_profit_or_charges(self):
        print("No profit or charges.")


class SavingsAccount(BankAccount):
    def calculate_profit_or_charges(self):
        profit = self.balance * 0.05
        print("Savings Account Profit: Rs.", profit)


class CurrentAccount(BankAccount):
    def calculate_profit_or_charges(self):
        charges = 500
        print("Current Account Charges: Rs.", charges)


# Create accounts
savings = SavingsAccount("SA001", "Ali", 100000)
current = CurrentAccount("CA001", "Ahmed", 150000)


# Select account
print("===== BANK ACCOUNT SYSTEM =====")
print("1. Savings Account")
print("2. Current Account")

choice = input("Select Account: ")

if choice == "1":
    account = savings
elif choice == "2":
    account = current
else:
    print("Invalid account choice.")
    exit()


# Bank menu
while True:
    print("\n===== BANK MENU =====")
    print("1. Deposit Money")
    print("2. Withdraw Money")
    print("3. Check Balance")
    print("4. Calculate Profit/Charges")
    print("5. Exit")

    option = input("Enter your choice: ")

    if option == "1":
        amount = float(input("Enter deposit amount: "))
        account.deposit(amount)

    elif option == "2":
        amount = float(input("Enter withdrawal amount: "))
        account.withdraw(amount)

    elif option == "3":
        account.check_balance()

    elif option == "4":
        account.calculate_profit_or_charges()

    elif option == "5":
        print("Thank you for using the Bank Account System.")
        break

    else:
        print("Invalid choice. Please try again.")