# -*- coding: utf-8 -*-
"""Bank account system maintance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17tt8lpuQKa_7NXtc2C_M4yb6SUNktozq
"""

class Account:
    def __init__(self, account_number, customer_name, balance):
        self.account_number = account_number
        self.customer_name = customer_name
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount
        print("Deposited: Rs.", amount)

    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance -= amount
            print("Withdrawn: Rs.", amount)
        else:
            print("Insufficient balance.")

    def display_account(self):
        print("Account Number:", self.account_number)
        print("Customer Name:", self.customer_name)
        print("Balance: Rs.", self.balance)

    def calculate_profit(self):
        print("No profit calculation for general account.")


class SavingsAccount(Account):
    def calculate_profit(self):
        profit = self.balance * 0.10
        print("Savings Account Profit: Rs.", profit)


class CurrentAccount(Account):
    def calculate_profit(self):
        profit = 0
        print("Current Account Profit: Rs.", profit)


class BusinessAccount(Account):
    def calculate_profit(self):
        profit = self.balance * 0.05
        print("Business Account Profit: Rs.", profit)


# Create Savings Account
savings = SavingsAccount("PK001", "Ali", 100000)

savings.display_account()
savings.deposit(20000)
savings.withdraw(10000)
savings.calculate_profit()

print()

# Create Current Account
current = CurrentAccount("PK002", "Ahmed", 150000)

current.display_account()
current.deposit(30000)
current.withdraw(20000)
current.calculate_profit()

print()

# Create Business Account
business = BusinessAccount("PK003", "Usman", 500000)

business.display_account()
business.deposit(100000)
business.withdraw(50000)
business.calculate_profit()