# -*- coding: utf-8 -*-
"""Family bussiness.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tt4EjrPA8UvygP-ApZ5wtbGNSQf0-1jN
"""

class BusinessOwner:
    def __init__(self, name, business_name, capital):
        self.name = name
        self.business_name = business_name
        self.capital = capital

    def display_business(self):
        print("Father's Name:", self.name)
        print("Business Name:", self.business_name)
        print("Capital: Rs.", self.capital)


class Son1(BusinessOwner):
    def manage_sales(self):
        print("Son 1 is responsible for managing sales.")


class Son2(BusinessOwner):
    def manage_finance(self):
        print("Son 2 is responsible for managing finance.")


class Daughter(BusinessOwner):
    def manage_marketing(self):
        print("Daughter is responsible for managing marketing.")


# Create objects
son1 = Son1("Ahmed", "Lahore Clothing Store", 5000000)
son2 = Son2("Ahmed", "Lahore Clothing Store", 5000000)
daughter = Daughter("Ahmed", "Lahore Clothing Store", 5000000)

# Display information and responsibilities
son1.display_business()
son1.manage_sales()

print()

son2.display_business()
son2.manage_finance()

print()

daughter.display_business()
daughter.manage_marketing()