# -*- coding: utf-8 -*-
"""final project :mini banking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1--J4P1HyHtdbjGxZ9xvvnTvCbM8uCjHf
"""

def check_balance(balance):
    print("Current Balance:", balance)


def deposit(balance, amount):
    if amount > 0:
        balance = balance + amount
        print("Deposit Successful")
        print("New Balance:", balance)
        return balance
    else:
        print("Deposit Rejected")
        print("Reason: Amount must be greater than 0")
        return balance


def withdraw(balance, amount):
    if amount <= 0:
        print("Withdrawal Rejected")
        print("Reason: Amount must be greater than 0")

    elif amount > balance:
        print("Withdrawal Rejected")
        print("Reason: Insufficient balance")

    elif balance - amount < 1000:
        print("Withdrawal Rejected")
        print("Reason: Remaining balance must be at least Rs. 1,000")

    else:
        balance = balance - amount
        print("Withdrawal Successful")
        print("Remaining Balance:", balance)

    return balance


def calculate_loan_eligibility(age, salary, credit_score):

    if age < 21:
        print("Loan Rejected")
        print("Reason: Age is below 21")

    elif salary < 50000:
        print("Loan Rejected")
        print("Reason: Salary is below Rs. 50,000")

    elif credit_score < 650:
        print("Loan Rejected")
        print("Reason: Credit score is below 650")

    else:
        print("Loan Approved")


# Starting balance
balance = 50000

while True:

    print("\n===== BANK SYSTEM =====")
    print("1. Check Balance")
    print("2. Deposit")
    print("3. Withdraw")
    print("4. Loan Eligibility")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":

        check_balance(balance)

    elif choice == "2":

        amount = float(input("Enter deposit amount: "))
        balance = deposit(balance, amount)

    elif choice == "3":

        amount = float(input("Enter withdrawal amount: "))
        balance = withdraw(balance, amount)

    elif choice == "4":

        age = int(input("Enter your age: "))
        salary = float(input("Enter your monthly salary: "))
        credit_score = int(input("Enter your credit score: "))

        calculate_loan_eligibility(
            age,
            salary,
            credit_score
        )

    elif choice == "5":

        print("Thank you for using the Bank System!")
        break

    else:

        print("Invalid choice. Please try again.")