# -*- coding: utf-8 -*-
"""Food delivery app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IV0p5IcDa7uB0KxjzjVBugzn-yFwbUF2
"""

class Food:
    def __init__(self, name, price, preparation_time):
        self.name = name
        self.price = price
        self.preparation_time = preparation_time

    def calculate_discount(self, quantity):
        return 0

    def display_info(self):
        print(
            self.name,
            "- Rs.", self.price,
            "- Preparation:", self.preparation_time, "minutes"
        )


class Pizza(Food):
    def calculate_discount(self, quantity):
        if quantity >= 2:
            return self.price * quantity * 0.10
        return 0


class Burger(Food):
    def calculate_discount(self, quantity):
        if quantity >= 2:
            return self.price * quantity * 0.05
        return 0


class Drink(Food):
    def calculate_discount(self, quantity):
        return 0


class Order:
    def __init__(self):
        self.items = []

    def add_food(self, food, quantity):
        self.items.append((food, quantity))
        print(quantity, food.name, "added to order.")

    def remove_food(self, food_name):
        for item in self.items:
            food, quantity = item

            if food.name.lower() == food_name.lower():
                self.items.remove(item)
                print(food_name, "removed from order.")
                return

        print("Food item not found.")

    def check_items(self):
        print("\n===== ORDER ITEMS =====")

        for food, quantity in self.items:
            print(
                quantity, "x", food.name,
                "= Rs.", food.price * quantity
            )

    def calculate_bill(self):
        total = 0
        total_discount = 0

        for food, quantity in self.items:
            subtotal = food.price * quantity
            discount = food.calculate_discount(quantity)

            total += subtotal
            total_discount += discount

        final_bill = total - total_discount

        print("\n===== BILL =====")
        print("Total Price: Rs.", total)
        print("Discount: Rs.", total_discount)
        print("Final Bill: Rs.", final_bill)

        return final_bill

    def place_order(self):
        print("\nOrder placed successfully!")
        print("Thank you for ordering.")


# Create food items
burger = Burger("Burger", 500, 15)
pizza = Pizza("Pizza", 1200, 25)
drink = Drink("Drink", 150, 5)


# Create order
order = Order()

# Customer orders:
# 2 burgers
# 1 pizza
# 2 drinks

order.add_food(burger, 2)
order.add_food(pizza, 1)
order.add_food(drink, 2)

# Check all items
order.check_items()

# Calculate bill
order.calculate_bill()

# Place order
order.place_order()