# -*- coding: utf-8 -*-
"""School management system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQwZo_bgHuNxcu6gVljyr85IS_aB058W
"""

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age


class Student(Person):
    def __init__(self, name, age, roll_no, marks):
        super().__init__(name, age)
        self.roll_no = roll_no
        self.marks = marks

    def calculate_total(self):
        return sum(self.marks.values())

    def calculate_percentage(self):
        total = self.calculate_total()
        return total / 5

    def calculate_grade(self):
        percentage = self.calculate_percentage()

        if percentage >= 80:
            return "A+"
        elif percentage >= 70:
            return "A"
        elif percentage >= 60:
            return "B"
        elif percentage >= 50:
            return "C"
        elif percentage >= 40:
            return "D"
        else:
            return "Fail"

    def display_result(self):
        print("\n===== STUDENT RESULT =====")
        print("Name:", self.name)
        print("Age:", self.age)
        print("Roll Number:", self.roll_no)

        print("\nSubject Marks:")

        for subject, mark in self.marks.items():
            print(subject, ":", mark)

        total = self.calculate_total()
        percentage = self.calculate_percentage()
        grade = self.calculate_grade()

        print("\nTotal Marks:", total, "/ 500")
        print("Percentage:", percentage, "%")
        print("Grade:", grade)


class Teacher(Person):
    def display_teacher(self):
        print("Teacher Name:", self.name)
        print("Age:", self.age)


# Create student
marks = {
    "English": 85,
    "Mathematics": 90,
    "Physics": 78,
    "Computer": 88,
    "Chemistry": 80
}

student = Student("Ali", 16, "101", marks)

# Create teacher
teacher = Teacher("Mr. Ahmed", 35)

# Display teacher
teacher.display_teacher()

# Display student result
student.display_result()

class RegularStudent(Student):
    def calculate_grade(self):
        return super().calculate_grade()


class ScholarshipStudent(Student):
    def calculate_grade(self):
        percentage = self.calculate_percentage()

        if percentage >= 75:
            return "Scholarship A+"
        elif percentage >= 60:
            return "Scholarship A"
        else:
            return "Scholarship Not Available"